<#
    .SYNOPSIS
    Reconciles the SharePoint Server User Profile Service Application against
    a JSON snapshot produced by SPSyncUserInfoList.ps1.

    .DESCRIPTION
    SPSyncUserProfile.ps1 reads the JSON file generated by
    SPSyncUserInfoList.ps1 and applies the same identity information into the
    User Profile Service Application (UPA) on the master server of the User
    Profile Service farm:

    - When the profile already exists, the script updates PreferredName,
      FirstName, LastName, WorkEmail and Country.
    - When the profile does not exist, the script creates it provided the
      account can still be resolved in Active Directory (via Test-SPSADUser).
    - Users missing FirstName, LastName or Email in the input JSON are
      written to a separate JSON for follow-up.

    The script is the multi-forest alternative to the built-in User Profile
    AD Import (UPA AD Import): it does not require a sync-time bind across
    every forest because the AD lookup has already been performed on the
    application farms.

    .PARAMETER InputFile
    Absolute path of the JSON file produced by SPSyncUserInfoList.ps1.

    .EXAMPLE
    SPSyncUserProfile.ps1 -InputFile 'D:\Tools\SCRIPTS\JOBS\SPSyncUserProfile\SPSyncUserInfoListUserList-CONTOSO.json'

    .NOTES
    FileName:   SPSyncUserProfile.ps1
    Author:     Jean-Cyril DROUHIN
    Project:    https://github.com/luigilink/SPSUserSync
#>
param
(
    [Parameter(Mandatory = $true)]
    [System.String]
    $InputFile
)

#region Import Modules
try {
    Import-Module -Name (Join-Path -Path $PSScriptRoot -ChildPath 'Modules\SPSUserSync.Common\SPSUserSync.Common.psd1') -Force -ErrorAction Stop
}
catch {
    Write-Error -Message @"
Failed to import SPSUserSync.Common module from path: $PSScriptRoot\Modules\SPSUserSync.Common
Exception: $_
"@
    Exit
}
#endregion

#region Classes
class SPSUserProfileMgmt {
    [System.String]$AccountName
    [System.String]$PreferredName
    [System.String]$FirstName
    [System.String]$LastName
    [System.String]$WorkEmail
    [System.String]$Country
    [System.String]$Status
    [System.String]$Date
    [System.String]$TimeStamp
}
#endregion

#region internal functions
function Add-SPSUserProfile {
    <#
        .SYNOPSIS
        Creates or updates one profile in the User Profile Service Application.
    #>
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory = $true)]
        [System.String]
        $UserLogin,

        [Parameter(Mandatory = $true)]
        [System.String]
        $PreferredName,

        [Parameter(Mandatory = $true)]
        [System.String]
        $FirstName,

        [Parameter(Mandatory = $true)]
        [System.String]
        $LastName,

        [Parameter(Mandatory = $true)]
        [System.String]
        $WorkEmail,

        [Parameter()]
        [System.String]
        $Country,

        [Parameter(Mandatory = $true)]
        [System.String]
        $MySiteUrl,

        [Parameter(Mandatory = $true)]
        [System.String]
        $ClaimPrefix,

        [Parameter(Mandatory = $true)]
        [System.Collections.ArrayList]
        $ResultCollection
    )

    $UserLogin           = $UserLogin.Replace($ClaimPrefix, '')
    $userProfileUpdated  = $false
    $spUserProfileStatus = 'INFO'
    $funcStarted         = Get-Date

    Write-Output '--------------------------------------------------------------'
    Write-Output "Manage $UserLogin in User Profile Service App - Started at $funcStarted"

    try {
        $spServiceContext     = Get-SPServiceContext -Site $MySiteUrl
        $spUserProfileManager = New-Object -TypeName Microsoft.Office.Server.UserProfiles.UserProfileManager($spServiceContext)

        if ($spUserProfileManager.UserExists($UserLogin)) {
            $getUserProfile = $spUserProfileManager.GetUserProfile($UserLogin)
            Write-Output '[SPUserProfiles.UserProfileManager.GetUserProfile] Current Values:'
            Write-Output "AccountName: $UserLogin"
            Write-Output "PreferredName: $($getUserProfile['PreferredName'].Value)"
            Write-Output "FirstName: $($getUserProfile['FirstName'].Value)"
            Write-Output "LastName: $($getUserProfile['LastName'].Value)"
            Write-Output "WorkEmail: $($getUserProfile['WorkEmail'].Value)"
            Write-Output "Country: $($getUserProfile['Country'].Value)"
            Write-Output '[SPUserProfiles.UserProfileManager.GetUserProfile] Target Values:'
            Write-Output "AccountName: $UserLogin"
            Write-Output "PreferredName: $PreferredName"
            Write-Output "FirstName: $FirstName"
            Write-Output "LastName: $LastName"
            Write-Output "WorkEmail: $WorkEmail"
            Write-Output "Country: $Country"

            if ($getUserProfile['WorkEmail'].Value -ne $WorkEmail) {
                $getUserProfile['WorkEmail'].Value = $WorkEmail
                $userProfileUpdated = $true
            }
            if ($getUserProfile['PreferredName'].Value -ne $PreferredName) {
                $getUserProfile['PreferredName'].Value = $PreferredName
                $userProfileUpdated = $true
            }
            if ($getUserProfile['FirstName'].Value -ne $FirstName) {
                $getUserProfile['FirstName'].Value = $FirstName
                $userProfileUpdated = $true
            }
            if ($getUserProfile['LastName'].Value -ne $LastName) {
                $getUserProfile['LastName'].Value = $LastName
                $userProfileUpdated = $true
            }
            if ($getUserProfile['Country'].Value -ne $Country -and -not [string]::IsNullOrEmpty($Country)) {
                $getUserProfile['Country'].Value = $Country
                $userProfileUpdated = $true
            }
            if ($userProfileUpdated) {
                $getUserProfile.Commit()
                $spUserProfileStatus = 'UPDATE'
            }
        }
        else {
            Write-Output '[SPUserProfiles.UserProfileManager.GetUserProfile] Current Values:'
            Write-Output "AccountName: $UserLogin"
            Write-Output 'PreferredName: NULL'
            Write-Output 'FirstName: NULL'
            Write-Output 'LastName: NULL'
            Write-Output 'WorkEmail: NULL'
            Write-Output 'Country: NULL'
            Write-Output '[SPUserProfiles.UserProfileManager.GetUserProfile] Target Values:'
            Write-Output "AccountName: $UserLogin"
            Write-Output "PreferredName: $PreferredName"
            Write-Output "FirstName: $FirstName"
            Write-Output "LastName: $LastName"
            Write-Output "WorkEmail: $WorkEmail"
            Write-Output "Country: $Country"
            $spUserProfileStatus = 'CREATE'
            if (Test-SPSADUser -UserLogin $UserLogin) {
                $spUserProfileManager.CreateUserProfile($UserLogin, $PreferredName)
                if (-not [string]::IsNullOrEmpty($WorkEmail)) {
                    $getUserProfile = $spUserProfileManager.GetUserProfile($UserLogin)
                    $getUserProfile['WorkEmail'].Value = $WorkEmail
                    if (-not [string]::IsNullOrEmpty($Country)) { $getUserProfile['Country'].Value = $Country }
                    $getUserProfile['FirstName'].Value = $FirstName
                    $getUserProfile['LastName'].Value  = $LastName
                    $getUserProfile.Commit()
                }
            }
            else {
                $spUserProfileStatus = 'UNKNOWN_USER'
            }
        }

        [void]$ResultCollection.Add([SPSUserProfileMgmt]@{
                AccountName   = $UserLogin
                PreferredName = $PreferredName
                FirstName     = $FirstName
                LastName      = $LastName
                WorkEmail     = $WorkEmail
                Country       = $Country
                Status        = $spUserProfileStatus
                Date          = (Get-Date -Format yyyyMMddTHHmmss)
                TimeStamp     = ((Get-Date).ToFileTime())
            })
    }
    catch {
        $catchMessage = @"
An error occurred while managing user '$UserLogin' in User Profile Service App
MySiteUrl: $MySiteUrl
Exception: $_
"@
        Add-SPSUserSyncEvent -Message $catchMessage -Source 'Add-SPSUserProfile' -EntryType 'Error'
    }

    Write-Output "Manage $UserLogin in User Profile Service App - Ended at $(Get-Date)"
    Write-Output '--------------------------------------------------------------'
}
#endregion

#region Main
# ===================================================================================
#
# SPSyncUserProfile Script - MAIN Region
#
# ===================================================================================
Clear-Host

# Bootstrap: admin check, transcript, banner (version read from the module manifest)
try {
    $ctx = Initialize-SPSScript -ScriptName 'SPSyncUserProfile' -ScriptRoot $PSScriptRoot
}
catch {
    Write-Error -Message $_.Exception.Message
    Exit
}

# Load InputFile
if (-not (Test-Path -Path $InputFile)) {
    $catchMessage = "InputFile not found: $InputFile"
    Add-SPSUserSyncEvent -Message $catchMessage -Source 'Test-Path' -EntryType 'Error'
    Stop-Transcript | Out-Null
    Throw $catchMessage
}

try {
    $psoSPSiteUsers = Get-Content -Path $InputFile -Raw -Encoding UTF8 | ConvertFrom-Json
}
catch {
    $catchMessage = @"
Failed to parse InputFile: $InputFile
Exception: $_
"@
    Add-SPSUserSyncEvent -Message $catchMessage -Source 'ConvertFrom-Json' -EntryType 'Error'
    Stop-Transcript | Out-Null
    Exit
}

# Load settings
try {
    $settings = Get-SPSSyncSetting
}
catch {
    $catchMessage = @"
An error occurred while loading sync-settings.psd1
Exception: $_
"@
    Add-SPSUserSyncEvent -Message $catchMessage -Source 'Get-SPSSyncSetting' -EntryType 'Error'
    Stop-Transcript | Out-Null
    Exit
}

# Rotate old logs
$upaRetention = if ($settings.UpaLogRetentionDays) { $settings.UpaLogRetentionDays } else { 30 }
Clear-SPSLogFolder -Path $ctx.LogFolder -Retention $upaRetention

# Load the SharePoint command surface (PSSnapin on 2013/2016/2019,
# SharePointServer module on Subscription Edition)
try {
    $spLoad = Import-SPSSharePointCommand
    Write-Output "SharePoint commands loaded via: $spLoad"
}
catch {
    $catchMessage = @"
An error occurred while loading the SharePoint command surface
Exception: $_
"@
    Add-SPSUserSyncEvent -Message $catchMessage -Source 'Import-SPSSharePointCommand' -EntryType 'Error'
    Stop-Transcript | Out-Null
    Exit
}

# Result paths
$pathUserAddedInUSPFile    = Join-Path -Path $ctx.LogFolder -ChildPath ('SPSyncUserAddedInUSPList' + (Get-Date -Format yyyyMMdd-HHmm) + '.json')
$pathUserNotAddedInUSPFile = Join-Path -Path $ctx.LogFolder -ChildPath ('SPSyncUserNotAddedInUSPList' + (Get-Date -Format yyyyMMdd-HHmm) + '.json')

# Validate MySite host
$spMySiteHostUrl = $settings.MySiteUrl
Write-Output "MySite Host Url: $spMySiteHostUrl"
$getMysiteHost = Get-SPSite $spMySiteHostUrl -ErrorAction SilentlyContinue
if ($null -eq $getMysiteHost) {
    $catchMessage = "SPSite Object $spMySiteHostUrl does not exist. Please check with your administrator."
    Add-SPSUserSyncEvent -Message $catchMessage -Source 'Get-SPSite' -EntryType 'Error'
    Stop-Transcript | Out-Null
    Throw $catchMessage
}

# Filter users with prerequisites
$usersWithPrerequisites    = $psoSPSiteUsers | Where-Object -FilterScript { -not ([string]::IsNullOrEmpty($_.FirstName) -or [string]::IsNullOrEmpty($_.LastName) -or [string]::IsNullOrEmpty($_.Email)) }
$usersWithoutPrerequisites = $psoSPSiteUsers | Where-Object -FilterScript { [string]::IsNullOrEmpty($_.FirstName) -or [string]::IsNullOrEmpty($_.LastName) -or [string]::IsNullOrEmpty($_.Email) }

# Process eligible users
$tbSPSUserProfileMgmt = New-Object -TypeName System.Collections.ArrayList
foreach ($psoSPSiteUser in $usersWithPrerequisites) {
    Add-SPSUserProfile `
        -UserLogin $psoSPSiteUser.UserLogin `
        -PreferredName $psoSPSiteUser.DisplayName `
        -FirstName $psoSPSiteUser.FirstName `
        -LastName $psoSPSiteUser.LastName `
        -WorkEmail $psoSPSiteUser.Email `
        -Country $psoSPSiteUser.Country `
        -MySiteUrl $spMySiteHostUrl `
        -ClaimPrefix $settings.ClaimPrefix `
        -ResultCollection $tbSPSUserProfileMgmt
}

Trap { Continue }
if ($usersWithoutPrerequisites.Count -ne 0) {
    Write-Output "$($usersWithoutPrerequisites.Count) users do not meet Prerequisites: First Name, Last Name and Email aren't filled."
    $usersWithoutPrerequisites | ConvertTo-Json | Set-Content -Path $pathUserNotAddedInUSPFile -Force -Encoding UTF8
    Write-Output "Saved User Profile Management in file: $pathUserNotAddedInUSPFile"
}
if ($tbSPSUserProfileMgmt.Count -ne 0) {
    Write-Output "$($tbSPSUserProfileMgmt.Count) users added/updated in User Profile Service Application"
    $tbSPSUserProfileMgmt | ConvertTo-Json | Set-Content -Path $pathUserAddedInUSPFile -Force -Encoding UTF8
    Write-Output "Saved User Profile Management in file: $pathUserAddedInUSPFile"

    # Generate the HTML report
    $generateHtml = if ($null -ne $settings.GenerateHtmlReport) { $settings.GenerateHtmlReport } else { $true }
    if ($generateHtml) {
        try {
            $reportFile = Join-Path -Path $ctx.LogFolder -ChildPath ('SPSyncUserProfileReport-' + (Get-Date -Format yyyyMMdd-HHmm) + '.html')
            $null = Export-SPSUserReport -InputObject $tbSPSUserProfileMgmt.ToArray() -ReportType 'UserProfile' -OutputFile $reportFile `
                -EnvName $settings.EnvName -AppCode $settings.AppCode -Version $ctx.Version
            Write-Output "HTML report written to: $reportFile"
            Clear-SPSLogFolder -Path $ctx.LogFolder -Retention $upaRetention -Extension '*.html'
        }
        catch {
            $catchMessage = @"
Failed to generate the HTML report
Exception: $_
"@
            Add-SPSUserSyncEvent -Message $catchMessage -Source 'Export-SPSUserReport' -EntryType 'Warning'
        }
    }
}

$DateEnded = Get-Date
Write-Output '-----------------------------------------------'
Write-Output '| Automated Script - Configuration SPSyncUserProfile'
Write-Output "| Started on       - $($ctx.DateStarted) |"
Write-Output "| Completed on     - $DateEnded |"
Write-Output '-----------------------------------------------'
Stop-Transcript
Exit
#endregion
