<#
    .SYNOPSIS
    Reconciles the SharePoint Server User Profile Service Application against
    a JSON snapshot produced by SPSyncUserInfoList.ps1.

    .DESCRIPTION
    SPSyncUserProfile.ps1 reads the JSON file generated by
    SPSyncUserInfoList.ps1 and applies the same identity information into the
    User Profile Service Application (UPA) on the master server of the User
    Profile Service farm:

    - When the profile already exists, the script updates PreferredName,
      FirstName, LastName, WorkEmail and Country.
    - When the profile does not exist, the script creates it provided the
      account can still be resolved in Active Directory (via Test-SPSADUser).
    - Users missing FirstName, LastName or Email in the input JSON are
      written to a separate JSON for follow-up, each tagged with a
      NotAddedReason (AD_NOT_FOUND, MISSING_ATTRIBUTES or DISABLED).
    - When SkipDisabledUsers is enabled in sync-settings.psd1, accounts flagged
      Disabled in the snapshot (AD userAccountControl) are reported as Not Added
      instead of being provisioned, so departed-but-retained accounts are skipped.

    Before processing, the script pre-flights the Active Directory configuration
    once per forest present in the input: if a forest's secrets.psd1 entry cannot
    be decoded on this server (DPAPI SecureStrings are bound to the machine and
    account that created them), the run stops immediately with an actionable
    message instead of silently downgrading every affected user to UNKNOWN_USER.

    The script is the multi-forest alternative to the built-in User Profile
    AD Import (UPA AD Import): it does not require a sync-time bind across
    every forest because the AD lookup has already been performed on the
    application farms.

    .PARAMETER InputFile
    Absolute path of the JSON file produced by SPSyncUserInfoList.ps1.

    .EXAMPLE
    SPSyncUserProfile.ps1 -InputFile 'D:\Tools\SCRIPTS\JOBS\SPSyncUserProfile\SPSyncUserInfoListUserList-CONTOSO.json'

    .NOTES
    FileName:   SPSyncUserProfile.ps1
    Author:     Jean-Cyril DROUHIN
    Project:    https://github.com/luigilink/SPSUserSync
#>
param
(
    [Parameter(Mandatory = $true)]
    [System.String]
    $InputFile
)

#region Import Modules
try {
    Import-Module -Name (Join-Path -Path $PSScriptRoot -ChildPath 'Modules\SPSUserSync.Common\SPSUserSync.Common.psd1') -Force -ErrorAction Stop
}
catch {
    Write-Error -Message @"
Failed to import SPSUserSync.Common module from path: $PSScriptRoot\Modules\SPSUserSync.Common
Exception: $_
"@
    Exit
}
#endregion

#region Classes
class SPSUserProfileMgmt {
    [System.String]$AccountName
    [System.String]$PreferredName
    [System.String]$FirstName
    [System.String]$LastName
    [System.String]$WorkEmail
    [System.String]$Country
    [System.String]$Status
    [System.String]$Date
    [System.String]$TimeStamp
}
#endregion

#region internal functions
function Add-SPSUserProfile {
    <#
        .SYNOPSIS
        Creates or updates one profile in the User Profile Service Application.
    #>
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory = $true)]
        [System.String]
        $UserLogin,

        [Parameter(Mandatory = $true)]
        [System.String]
        $PreferredName,

        [Parameter(Mandatory = $true)]
        [System.String]
        $FirstName,

        [Parameter(Mandatory = $true)]
        [System.String]
        $LastName,

        [Parameter(Mandatory = $true)]
        [System.String]
        $WorkEmail,

        [Parameter()]
        [System.String]
        $Country,

        [Parameter(Mandatory = $true)]
        [System.String]
        $MySiteUrl,

        [Parameter(Mandatory = $true)]
        [System.String]
        $ClaimPrefix,

        [Parameter(Mandatory = $true)]
        [AllowEmptyCollection()]
        [System.Collections.ArrayList]
        $ResultCollection
    )

    $UserLogin           = $UserLogin.Replace($ClaimPrefix, '')
    $userProfileUpdated  = $false
    $spUserProfileStatus = 'INFO'
    $funcStarted         = Get-Date

    Write-Output '--------------------------------------------------------------'
    Write-Output "Manage $UserLogin in User Profile Service App - Started at $funcStarted"

    try {
        $spServiceContext     = Get-SPServiceContext -Site $MySiteUrl
        $spUserProfileManager = New-Object -TypeName Microsoft.Office.Server.UserProfiles.UserProfileManager($spServiceContext)

        if ($spUserProfileManager.UserExists($UserLogin)) {
            $getUserProfile = $spUserProfileManager.GetUserProfile($UserLogin)
            Write-Output '[SPUserProfiles.UserProfileManager.GetUserProfile] Current Values:'
            Write-Output "AccountName: $UserLogin"
            Write-Output "PreferredName: $($getUserProfile['PreferredName'].Value)"
            Write-Output "FirstName: $($getUserProfile['FirstName'].Value)"
            Write-Output "LastName: $($getUserProfile['LastName'].Value)"
            Write-Output "WorkEmail: $($getUserProfile['WorkEmail'].Value)"
            Write-Output "Country: $($getUserProfile['Country'].Value)"
            Write-Output '[SPUserProfiles.UserProfileManager.GetUserProfile] Target Values:'
            Write-Output "AccountName: $UserLogin"
            Write-Output "PreferredName: $PreferredName"
            Write-Output "FirstName: $FirstName"
            Write-Output "LastName: $LastName"
            Write-Output "WorkEmail: $WorkEmail"
            Write-Output "Country: $Country"

            if ($getUserProfile['WorkEmail'].Value -ne $WorkEmail) {
                $getUserProfile['WorkEmail'].Value = $WorkEmail
                $userProfileUpdated = $true
            }
            if ($getUserProfile['PreferredName'].Value -ne $PreferredName) {
                $getUserProfile['PreferredName'].Value = $PreferredName
                $userProfileUpdated = $true
            }
            if ($getUserProfile['FirstName'].Value -ne $FirstName) {
                $getUserProfile['FirstName'].Value = $FirstName
                $userProfileUpdated = $true
            }
            if ($getUserProfile['LastName'].Value -ne $LastName) {
                $getUserProfile['LastName'].Value = $LastName
                $userProfileUpdated = $true
            }
            if ($getUserProfile['Country'].Value -ne $Country -and -not [string]::IsNullOrEmpty($Country)) {
                $getUserProfile['Country'].Value = $Country
                $userProfileUpdated = $true
            }
            if ($userProfileUpdated) {
                $getUserProfile.Commit()
                $spUserProfileStatus = 'UPDATE'
            }
        }
        else {
            Write-Output '[SPUserProfiles.UserProfileManager.GetUserProfile] Current Values:'
            Write-Output "AccountName: $UserLogin"
            Write-Output 'PreferredName: NULL'
            Write-Output 'FirstName: NULL'
            Write-Output 'LastName: NULL'
            Write-Output 'WorkEmail: NULL'
            Write-Output 'Country: NULL'
            Write-Output '[SPUserProfiles.UserProfileManager.GetUserProfile] Target Values:'
            Write-Output "AccountName: $UserLogin"
            Write-Output "PreferredName: $PreferredName"
            Write-Output "FirstName: $FirstName"
            Write-Output "LastName: $LastName"
            Write-Output "WorkEmail: $WorkEmail"
            Write-Output "Country: $Country"
            $spUserProfileStatus = 'CREATE'
            if (Test-SPSADUser -UserLogin $UserLogin) {
                $spUserProfileManager.CreateUserProfile($UserLogin, $PreferredName)
                if (-not [string]::IsNullOrEmpty($WorkEmail)) {
                    $getUserProfile = $spUserProfileManager.GetUserProfile($UserLogin)
                    $getUserProfile['WorkEmail'].Value = $WorkEmail
                    if (-not [string]::IsNullOrEmpty($Country)) { $getUserProfile['Country'].Value = $Country }
                    $getUserProfile['FirstName'].Value = $FirstName
                    $getUserProfile['LastName'].Value  = $LastName
                    $getUserProfile.Commit()
                }
            }
            else {
                $spUserProfileStatus = 'UNKNOWN_USER'
            }
        }

        [void]$ResultCollection.Add([SPSUserProfileMgmt]@{
                AccountName   = $UserLogin
                PreferredName = $PreferredName
                FirstName     = $FirstName
                LastName      = $LastName
                WorkEmail     = $WorkEmail
                Country       = $Country
                Status        = $spUserProfileStatus
                Date          = (Get-Date -Format yyyyMMddTHHmmss)
                TimeStamp     = ((Get-Date).ToFileTime())
            })
    }
    catch {
        $catchMessage = @"
An error occurred while managing user '$UserLogin' in User Profile Service App
MySiteUrl: $MySiteUrl
Exception: $_
"@
        Add-SPSUserSyncEvent -Message $catchMessage -Source 'Add-SPSUserProfile' -EntryType 'Error'
    }

    Write-Output "Manage $UserLogin in User Profile Service App - Ended at $(Get-Date)"
    Write-Output '--------------------------------------------------------------'
}

function Split-SPSProfileUser {
    <#
        .SYNOPSIS
        Partitions the input users into the profiles to provision and the ones to
        leave out, tagging every excluded user with a NotAddedReason.

        .DESCRIPTION
        A user is eligible for a User Profile only when it has the required
        attributes (FirstName, LastName and Email) AND is not being deliberately
        skipped for being disabled in Active Directory.

        Excluded users are annotated with a NotAddedReason so the operator can tell
        an expected miss from an actionable one:
        - 'AD_NOT_FOUND'      : the account no longer resolves in AD (deleted /
                                departed, or a forest not declared in ad-domains.psd1)
                                - it has no attributes AND AccountStatus 'NotFound'.
        - 'MISSING_ATTRIBUTES': resolved but FirstName, LastName or Email is empty.
        - 'DISABLED'          : has all attributes but the AD account is disabled and
                                SkipDisabledUsers is on.

        The disabled gate relies only on the universal AccountStatus tag written by
        SPSyncUserInfoList.ps1 (from userAccountControl), so it behaves identically
        for every customer. Snapshots produced before 1.3.3 carry no AccountStatus,
        so no user is skipped as disabled until a fresh snapshot is generated.

        .PARAMETER User
        The users loaded from the input JSON.

        .PARAMETER SkipDisabledUsers
        When $true, users whose AccountStatus is 'Disabled' are excluded from
        provisioning. Default $false preserves the pre-1.3.3 behaviour.

        .OUTPUTS
        A hashtable with two ArrayLists: Eligible and NotAdded.
    #>
    [CmdletBinding()]
    [OutputType([System.Collections.Hashtable])]
    param
    (
        [Parameter(Mandatory = $true)]
        [AllowEmptyCollection()]
        [System.Object[]]
        $User,

        [Parameter()]
        [System.Boolean]
        $SkipDisabledUsers = $false
    )

    $eligible = New-Object System.Collections.ArrayList
    $notAdded = New-Object System.Collections.ArrayList

    foreach ($u in $User) {
        $missingAttributes = [string]::IsNullOrEmpty($u.FirstName) -or
            [string]::IsNullOrEmpty($u.LastName) -or
            [string]::IsNullOrEmpty($u.Email)
        $isDisabled = ($u.AccountStatus -eq 'Disabled')

        if (-not $missingAttributes -and -not ($SkipDisabledUsers -and $isDisabled)) {
            [void]$eligible.Add($u)
            continue
        }

        if ($missingAttributes) {
            $reason = if ($u.AccountStatus -eq 'NotFound') { 'AD_NOT_FOUND' } else { 'MISSING_ATTRIBUTES' }
        }
        else {
            # Reached only via the SkipDisabledUsers gate (attributes are present).
            $reason = 'DISABLED'
        }

        [void]$notAdded.Add(($u | Add-Member -NotePropertyName 'NotAddedReason' -NotePropertyValue $reason -PassThru -Force))
    }

    return @{ Eligible = $eligible; NotAdded = $notAdded }
}
#endregion

#region Main
# ===================================================================================
#
# SPSyncUserProfile Script - MAIN Region
#
# ===================================================================================
Clear-Host

# Bootstrap: admin check, transcript, banner (version read from the module manifest)
try {
    $ctx = Initialize-SPSScript -ScriptName 'SPSyncUserProfile' -ScriptRoot $PSScriptRoot
}
catch {
    Write-Error -Message $_.Exception.Message
    Exit
}

# Load InputFile
if (-not (Test-Path -Path $InputFile)) {
    $catchMessage = "InputFile not found: $InputFile"
    Add-SPSUserSyncEvent -Message $catchMessage -Source 'Test-Path' -EntryType 'Error'
    Stop-Transcript | Out-Null
    Throw $catchMessage
}

try {
    $psoSPSiteUsers = Get-Content -Path $InputFile -Raw -Encoding UTF8 | ConvertFrom-Json
}
catch {
    $catchMessage = @"
Failed to parse InputFile: $InputFile
Exception: $_
"@
    Add-SPSUserSyncEvent -Message $catchMessage -Source 'ConvertFrom-Json' -EntryType 'Error'
    Stop-Transcript | Out-Null
    Exit
}

# Load settings
try {
    $settings = Get-SPSSyncSetting
}
catch {
    $catchMessage = @"
An error occurred while loading sync-settings.psd1
Exception: $_
"@
    Add-SPSUserSyncEvent -Message $catchMessage -Source 'Get-SPSSyncSetting' -EntryType 'Error'
    Stop-Transcript | Out-Null
    Exit
}

# Rotate old logs
$upaRetention = if ($settings.UpaLogRetentionDays) { $settings.UpaLogRetentionDays } else { 30 }
Clear-SPSLogFolder -Path $ctx.LogFolder -Retention $upaRetention

# Load the SharePoint command surface (PSSnapin on 2013/2016/2019,
# SharePointServer module on Subscription Edition)
try {
    $spLoad = Import-SPSSharePointCommand
    Write-Output "SharePoint commands loaded via: $spLoad"
}
catch {
    $catchMessage = @"
An error occurred while loading the SharePoint command surface
Exception: $_
"@
    Add-SPSUserSyncEvent -Message $catchMessage -Source 'Import-SPSSharePointCommand' -EntryType 'Error'
    Stop-Transcript | Out-Null
    Exit
}

# Result paths
$pathUserAddedInUSPFile    = Join-Path -Path $ctx.LogFolder -ChildPath ('SPSyncUserAddedInUSPList' + (Get-Date -Format yyyyMMdd-HHmm) + '.json')
$pathUserNotAddedInUSPFile = Join-Path -Path $ctx.LogFolder -ChildPath ('SPSyncUserNotAddedInUSPList' + (Get-Date -Format yyyyMMdd-HHmm) + '.json')

# Validate MySite host
$spMySiteHostUrl = $settings.MySiteUrl
Write-Output "MySite Host Url: $spMySiteHostUrl"
$getMysiteHost = Get-SPSite $spMySiteHostUrl -ErrorAction SilentlyContinue
if ($null -eq $getMysiteHost) {
    $catchMessage = "SPSite Object $spMySiteHostUrl does not exist. Please check with your administrator."
    Add-SPSUserSyncEvent -Message $catchMessage -Source 'Get-SPSite' -EntryType 'Error'
    Stop-Transcript | Out-Null
    Throw $catchMessage
}

# Filter users with prerequisites. AD-disabled accounts are optionally excluded
# (opt-in SkipDisabledUsers, default $false = pre-1.3.3 behaviour), so a departed
# employee whose account is disabled-but-retained does not get a profile. The gate
# reads only the universal AccountStatus tag from the input JSON, so it works for
# every customer regardless of their leaver process.
$skipDisabled = if ($null -ne $settings.SkipDisabledUsers) { [System.Boolean]$settings.SkipDisabledUsers } else { $false }
if ($skipDisabled) {
    Write-Output 'SkipDisabledUsers is enabled: AD-disabled accounts will be reported as Not Added instead of provisioned.'
}
$splitUsers                = Split-SPSProfileUser -User @($psoSPSiteUsers) -SkipDisabledUsers $skipDisabled
$usersWithPrerequisites    = $splitUsers.Eligible
$usersWithoutPrerequisites = $splitUsers.NotAdded

# Pre-flight the AD configuration once per forest BEFORE the loop. Profiles are only
# created for users that still resolve in AD (Test-SPSADUser), so a secrets.psd1 that
# cannot be decoded on THIS server would otherwise downgrade every affected user to
# UNKNOWN_USER, silently, one Event-Log line at a time. Validate each distinct forest
# up front and fail fast with an actionable message instead.
$preflightErrors = @(Get-SPSADConnectionError -UserLogin @($usersWithPrerequisites.UserLogin))
if ($preflightErrors.Count -ne 0) {
    $preflightDetail = ($preflightErrors | ForEach-Object { "$($_.Domain) - $($_.Error)" }) -join "`r`n"
    $failMessage = @"
User Profile sync aborted: the Active Directory configuration/secret could not be validated on this server for $($preflightErrors.Count) forest(s):
$preflightDetail

secrets.psd1 must be regenerated on THIS server, as the service account that runs this script (DPAPI SecureStrings are bound to the machine + account that created them). Run Test-SPSUserSyncReadiness.ps1 here to confirm, then re-run. Without this, users in these forests would be silently skipped as UNKNOWN_USER.
"@
    Write-Error -Message $failMessage -ErrorAction Continue
    Add-SPSUserSyncEvent -Message $failMessage -Source 'SPSyncUserProfile' -EntryType 'Error'
    Stop-Transcript | Out-Null
    Exit 1
}

# Process eligible users
$tbSPSUserProfileMgmt = New-Object -TypeName System.Collections.ArrayList
foreach ($psoSPSiteUser in $usersWithPrerequisites) {
    try {
        Add-SPSUserProfile `
            -UserLogin $psoSPSiteUser.UserLogin `
            -PreferredName $psoSPSiteUser.DisplayName `
            -FirstName $psoSPSiteUser.FirstName `
            -LastName $psoSPSiteUser.LastName `
            -WorkEmail $psoSPSiteUser.Email `
            -Country $psoSPSiteUser.Country `
            -MySiteUrl $spMySiteHostUrl `
            -ClaimPrefix $settings.ClaimPrefix `
            -ResultCollection $tbSPSUserProfileMgmt
    }
    catch {
        $catchMessage = @"
An error occurred while managing user '$($psoSPSiteUser.UserLogin)' in the User Profile Service App
MySiteUrl: $spMySiteHostUrl
Exception: $_
"@
        Write-Warning -Message $catchMessage
        Add-SPSUserSyncEvent -Message $catchMessage -Source 'Add-SPSUserProfile' -EntryType 'Error'
    }
}

if ($usersWithoutPrerequisites.Count -ne 0) {
    $missingCount  = @($usersWithoutPrerequisites | Where-Object { $_.NotAddedReason -eq 'MISSING_ATTRIBUTES' }).Count
    $notFoundCount = @($usersWithoutPrerequisites | Where-Object { $_.NotAddedReason -eq 'AD_NOT_FOUND' }).Count
    $disabledCount = @($usersWithoutPrerequisites | Where-Object { $_.NotAddedReason -eq 'DISABLED' }).Count
    Write-Output "$($usersWithoutPrerequisites.Count) user(s) not added to the User Profile Service Application (missing attributes: $missingCount, not found in AD: $notFoundCount, disabled: $disabledCount)."
    $usersWithoutPrerequisites | ConvertTo-Json | Set-Content -Path $pathUserNotAddedInUSPFile -Force -Encoding UTF8
    Write-Output "Saved User Profile Management in file: $pathUserNotAddedInUSPFile"
}
if ($tbSPSUserProfileMgmt.Count -ne 0) {
    Write-Output "$($tbSPSUserProfileMgmt.Count) users added/updated in User Profile Service Application"
    $tbSPSUserProfileMgmt | ConvertTo-Json | Set-Content -Path $pathUserAddedInUSPFile -Force -Encoding UTF8
    Write-Output "Saved User Profile Management in file: $pathUserAddedInUSPFile"

    # Generate the HTML report
    $generateHtml = if ($null -ne $settings.GenerateHtmlReport) { $settings.GenerateHtmlReport } else { $true }
    if ($generateHtml) {
        try {
            $reportFile = Join-Path -Path $ctx.LogFolder -ChildPath ('SPSyncUserProfileReport-' + (Get-Date -Format yyyyMMdd-HHmm) + '.html')
            $null = Export-SPSUserReport -InputObject $tbSPSUserProfileMgmt.ToArray() -ReportType 'UserProfile' -OutputFile $reportFile `
                -EnvName $settings.EnvName -AppCode $settings.AppCode -Version $ctx.Version
            Write-Output "HTML report written to: $reportFile"
            Clear-SPSLogFolder -Path $ctx.LogFolder -Retention $upaRetention -Extension '*.html'
        }
        catch {
            $catchMessage = @"
Failed to generate the HTML report
Exception: $_
"@
            Add-SPSUserSyncEvent -Message $catchMessage -Source 'Export-SPSUserReport' -EntryType 'Warning'
        }
    }
}

$DateEnded = Get-Date
Write-Output '-----------------------------------------------'
Write-Output '| Automated Script - Configuration SPSyncUserProfile'
Write-Output "| Started on       - $($ctx.DateStarted) |"
Write-Output "| Completed on     - $DateEnded |"
Write-Output '-----------------------------------------------'
Stop-Transcript
Exit
#endregion
